# Generated by Django 6.1 on 2026-08-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('importance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('learning_order', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.course')),
            ],
            options={
                'db_table': 'topic',
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PYQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField()),
                ('marks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('question_text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.topic')),
            ],
            options={
                'db_table': 'pyq_question',
            },
        ),
        migrations.CreateModel(
            name='TopicDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='planner.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='planner.topic')),
            ],
            options={
                'db_table': 'topic_dependency',
            },
        ),
    ]
