# Generated by Django 6.1 on 2026-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_studentprofile_usercourserating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance_weight', models.DecimalField(decimal_places=2, default=0.4, max_digits=3)),
                ('difficulty_weight', models.DecimalField(decimal_places=2, default=0.35, max_digits=3)),
                ('frequency_weight', models.DecimalField(decimal_places=2, default=0.25, max_digits=3)),
                ('revision_percent', models.DecimalField(decimal_places=1, default=20.0, max_digits=4)),
            ],
            options={
                'db_table': 'plan_setting',
            },
        ),
    ]
