# Generated by Django 6.1 on 2026-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_plansetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyqquestion',
            name='term',
            field=models.CharField(default='', max_length=20),
        ),
    ]
